version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  pre_build:
    commands:
      - echo start testing
      - npm run test
      - npx codecov -t ${CODECOV_TOKEN} -b ${GITHUB_BRANCH}
      - echo end testing
  build:
    commands:
      - echo start deploying
      - |
        if [ "${GITHUB_BRANCH}" = "master" ]; then
          STAGE_NAME=prod
        fi
      - npx sls deploy -s ${STAGE_NAME}
      - echo end deploying
  post_build:
    commands:
      - echo Deployment completed on `date`