service: majo21-backend

plugins:
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:service}-db-${self:custom.stage}
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  individually: true

resources:
  - ${file(resources/dynamodb-table.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
    DYNAMODB_ENDPOINT_LOCAL: ${env:DYNAMODB_ENDPOINT_LOCAL}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    GITHUB_WEBHOOK_SECRET: ${env:GITHUB_WEBHOOK_SECRET}
    GITHUB_ENDPOINT: ${env:GITHUB_ENDPOINT}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ MainTable, Arn ]
        - "Fn::Join":
            - '/'
            -
              - "Fn::GetAtt": [ MainTable, Arn ]
              - "index/*"

functions:
  authGithook:
    handler: auth.githook
    cors: true
  getPost:
    handler: api/getPost.main
  deletePost:
    handler: api/deletePost.main
  getPosts:
    handler: api/getPosts.main
    events:
      - http:
          path: posts/t/{postType}
          method: get
          cors: true
  loadPosts:
    handler: api/loadPosts.main
  updatePosts:
    handler: api/updatePosts.main
    events:
      - http:
          path: webhooks/github/e/push
          method: post
          authorizer: authGithook
