service: majo21-backend

plugins:
  - serverless-dynamodb-local
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:service}-db-${self:custom.stage}
  dynamodb:
    start:
      migrate: true
    stages:
      - dev
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  individually: true

resources:
  Resources:
    MainTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1
            AttributeType: S
          - AttributeName: GSI2
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1
                KeyType: HASH
              - AttributeName: SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: GSI2
            KeySchema:
              - AttributeName: GSI2
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
    DYNAMODB_ENDPOINT_LOCAL: http://localhost:8000
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    GITHUB_WEBHOOK_SECRET: ${env:GITHUB_WEBHOOK_SECRET}
    GITHUB_BRANCH: ${env:GITHUB_BRANCH}
    GITHUB_ENDPOINT: ${env:GITHUB_ENDPOINT}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ MainTable, Arn ]
        - "Fn::Join":
            - '/'
            -
              - "Fn::GetAtt": [ MainTable, Arn ]
              - "index/*"

functions:
  getPost:
    handler: src/api/getPost.main
  deletePost:
    handler: src/api/deletePost.main
  getPosts:
    handler: src/api/getPosts.main
    events:
      - http:
          path: posts/t/{postType}
          method: get
          cors: true
  loadPosts:
    handler: src/api/loadPosts.main
  updatePosts:
    handler: src/api/updatePosts.main
    events:
      - http:
          path: webhooks/github/e/push
          method: post
  getAllSeries:
    handler: src/api/getAllSeries.main
    events:
      - http:
          path: series
          method: get
          cors: true
  getPostsBySeries:
    handler: src/api/getPostsBySeries.main
    events:
      - http:
          path: posts/s/{seriesId}
          method: get
          cors: true
