service: majo21-backend

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:service}-db-${self:custom.stage}
  dynamodb:
    stages:
      - dev

resources:
  - ${file(resources/dynamodb-table.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:custom.tableName}
    DYNAMODB_ENDPOINT_LOCAL: ${env:DYNAMODB_ENDPOINT_LOCAL}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    GITHUB_ENDPOINT: ${env:GITHUB_ENDPOINT}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ MainTable, Arn ]

functions:
  getPosts:
    handler: api/getPosts.main
    events:
      - http:
          path: posts/t/{type}/{id}
          method: get
          cors: true
  loadPosts:
    handler: api/loadPosts.main
  updatePosts:
    handler: api/updatePosts.main
    events:
      - http:
          path: webhooks/github/e/push
          method: post
